Agent taps
ns1labs/orb-website pull request #27
Opened 2022-11-09 12:38 UTC by manrodrigues

This PR inserts the taps information in the Agent's documentation and complements the structure of the policies

2022-11-09 18:29 UTC, weyrick requested changes
good start, but let's be careful about how we talk about the pktvisor backend - we should do it in a way that does not require us to update the documentation everywhere when we release more backends

2022-11-09 18:29 UTC, weyrick commented on docs/documentation/advanced_policies.md
> +An Orb policy must be written in json and has sevem top level sections: `name`, `desciption`, `tags`, `backend`, `schema_version`, `policy` and `format`.
typo `seven`. we need to discuss how they can use YAML

2022-11-09 18:29 UTC, weyrick commented on docs/documentation/advanced_policies.md
> +The only option nowadays is `pktvisor`.<br><br>
i do not want to say that the only option is pktvisor - that will get outdated. we should link to another part of the documentation listing the current builtin available backend options

2022-11-09 18:29 UTC, weyrick commented on docs/documentation/advanced_policies.md
> +Each backend supported on Orb must have a policy schema to be validated, parsed and applied. `schema_version` is the field responsible for allowing different schema versions and backward compatibilit
Again, don't mention pktvisor, but ok to say "default should be 1.0"

2022-11-09 18:29 UTC, weyrick commented on docs/documentation/advanced_policies.md
> +Currently, the only backend supported by Orb is `pktvisor`. For that reason, the policy must have pktvisor's format.<br><br>
remove this sentence

2022-11-09 18:29 UTC, weyrick commented on docs/documentation/running_orb_agent.md
> +## Agent Taps
preface this section with a header specifying that this section is pktvisor configuration (under the `visor` top level key), and is specific to pktvisor backend

2022-11-29 22:05 UTC, manrodrigues commented on docs/documentation/advanced_policies.md
> +An Orb policy must be written in json and has sevem top level sections: `name`, `desciption`, `tags`, `backend`, `schema_version`, `policy` and `format`.
hum.. if i'm not wrong, only the policy section inside policy (it is confusing :s ) can be written in json or yaml.. the entire policy must be written in json..

2022-11-29 22:07 UTC, manrodrigues commented on docs/documentation/advanced_policies.md
> +Currently, the only backend supported by Orb is `pktvisor`. For that reason, the policy must have pktvisor's format.<br><br>
The format sentence as well? I changed this part.. please check it again.. if you still want to me to remove/change, please let me know..

2022-11-29 22:12 UTC, manrodrigues commented on docs/documentation/running_orb_agent.md
> +## Agent Taps
I inserted a new file with orb agents backend information.. and I referenced this file in the places that mentioned pktvisor before. please let me know what you think about it. It's an idea.. we can change, remove, adapt.. no problems :)

2022-12-01 19:18 UTC, weyrick requested changes
great just few small changes now

2022-12-01 19:18 UTC, weyrick commented on docs/documentation/advanced_policies.md
> +An Orb policy must be written in json and has seven top level sections: `name`, `desciption`, `tags`, `backend`, `schema_version`, `policy` and `format`.
Ok let's avoid confusion here then. Since all REST API calls "must be written in json" then I don't think there is any reason to state that here. We can just say:

"The policy model has seven top level sections..."

2022-12-01 19:18 UTC, weyrick commented on docs/documentation/orb_agent_backend.md
> +It is worth emphasizing that no extra installation is necessary, since the agent itself already has native support for its backends.
"...since the `orb-agent` docker container already includes the available backends"

2022-12-01 21:28 UTC, weyrick approved these changes

2022-12-02 13:18 UTC, merged