orb status documentation
ns1labs/orb-website pull request #5
Opened 2022-06-28 12:25 UTC by manrodrigues

The intention here is to provide more information and explanations of how to interpret the system to the user.

2022-06-28 20:53 UTC, weyrick requested changes

2022-06-28 20:53 UTC, weyrick commented on docs/docs.md
> +🟣 `new` means that the agent never received a heartbeat (never ran).
`new` means that the agent never sent a heartbeat (i.e. has never connected to the control plane).

2022-06-28 20:53 UTC, weyrick commented on docs/docs.md
> +🟢 `online` means that the agent is receiving heartbeats right now (is running and healthy).
the agent is "sending", not receiving

2022-06-28 20:53 UTC, weyrick commented on docs/docs.md
> +⚪ `offline` means that the agent received a heartbeat saying it is going offline.
`offline` means that the control plane received a heartbeat saying that the agent is going offline.

2022-06-28 20:53 UTC, weyrick commented on docs/docs.md
> +🟠 `stale` means that the agent has not received a heartbeat for 5 minutes without having received a heartbeat stating that it would go offline
`stale` means that the control plane has not received a heartbeat for 5 minutes

2022-06-28 20:53 UTC, weyrick commented on docs/docs.md
> +)
extra ")"?

2022-06-28 20:53 UTC, weyrick commented on docs/docs.md
> +<span style="color:green">running</span> if agent policy is being managed from core (policy-related metrics are being requested/scraped by this agent)
let's consistently use "control plane" instead of "core"

2022-06-28 20:53 UTC, weyrick commented on docs/docs.md
> +<span style="color:red">failled_to_apply</span> if an error prevents the policy from being sent to the group. By clicking on the expand icon you can see the cause of the error
"if an error prevents the policy from being applied by the agent"

2022-06-28 20:53 UTC, weyrick commented on docs/docs.md
> +The dataset will always be `valid` as long as the policy, the group *AND* the sink linked to it exist in the orb. If the policy, the group *OR* the sink is removed from the orb, the dataset will be `
The dataset will always be `valid` as long as the policy, the group *AND* the sink linked to it exist in Orb. If the policy, the group *OR* the sink is removed from Orb, the dataset will become `invalid`. Note, in the image above, that the invalid dataset does not contain the group listed, as it has been removed from Orb.

2022-06-28 20:53 UTC, weyrick commented on docs/docs.md
> +🟠 `Unknown` - No metrics have ever been scraped and published by this sink
No metrics have ever been published to this sink

2022-06-28 20:53 UTC, weyrick commented on docs/docs.md
> +🟢 `Active` - Metrics are being scraped and published by this sink
Metrics are actively being published to this sink

2022-06-28 20:53 UTC, weyrick commented on docs/docs.md
> +⚪ `Idle` - The last metrics scraped and published by this sink were more than 1 minutes ago (metrics are no longer being scraped/published in this sink)
The last metrics published to this sink were more than 5 minutes ago

2022-06-28 20:53 UTC, weyrick commented on docs/docs.md
> +🔴 `Error`  - The sink tried to scrape and publish the metrics but failed. **Attention: you will not be able to see your data in Grafana. In this case, check that the Grafana credentials were passed c
The sink tried to publish metrics but failed. **Attention: In this case, check that the sink credentials are configured correctly.**

2022-06-28 20:53 UTC, weyrick commented on docs/docs.md
> +    === "You may want to run more than one agent on the same network and for that you must specify different ports for them, since only one agent is allowed to run per port. By default, the agent con
You may want to run more than one agent on the same node and for that you must specify different pktvisor control ports for them, since the containers run in host networking mode, only one is allowed to run per port. By default, the pktvisor control port runs on port *10853*, but this value can be set through the environment variable `ORB_BACKENDS_PKTVISOR_API_PORT`

2022-06-29 18:22 UTC, manrodrigues commented
@weyrick  Many thanks for taking the time to review each item. Very cool to have the technically accurate description of each status. I applied the corrections. If you have any further considerations, please let me know.

2022-06-30 15:22 UTC, merged